export const types = {
  SEND_REQUEST_DARK_MODE: 'SEND_REQUEST_DARK_MODE',
  SEND_REQUEST_DARK_MODE_SUCCESS: 'SEND_REQUEST_DARK_MODE_SUCCESS',
  SEND_REQUEST_DARK_MODE_FAILURE: 'SEND_REQUEST_DARK_MODE_FAILURE',

  SEND_REQUEST_GET_USER: 'SEND_REQUEST_GET_USER',
  SEND_REQUEST_CLEAR_USER: 'SEND_REQUEST_CLEAR_USER',
  SEND_REQUEST_GET_USER_SUCCESS: 'SEND_REQUEST_GET_USER_SUCCESS',
  SEND_REQUEST_GET_ALL_USER_FAILURE: 'SEND_REQUEST_GET_ALL_USER_FAILURE',

  SEND_REQUEST_GET_DETAILS_PYC: 'SEND_REQUEST_GET_DETAILS_PYC',
  SEND_REQUEST_GET_DETAILS_PYC_SUCCESS: 'SEND_REQUEST_GET_DETAILS_PYC_SUCCESS',
  SEND_REQUEST_GET_DETAILS_PYC_FAILURE: 'SEND_REQUEST_GET_DETAILS_PYC_FAILURE',

  SEND_REQUEST_GET_DETAILS_USER: 'SEND_REQUEST_GET_DETAILS_USER',
  SEND_REQUEST_GET_DETAILS_USER_SUCCESS: 'SEND_REQUEST_GET_DETAILS_USER_SUCCESS',
  SEND_REQUEST_GET_DETAILS_USER_FAILURE: 'SEND_REQUEST_GET_DETAILS_USER_FAILURE',
  SEND_REQUEST_DELETE_USER: 'SEND_REQUEST_DELETE_USER',
  SEND_REQUEST_DELETE_USER_SUCCESS: 'SEND_REQUEST_DELETE_USER_SUCCESS',
  SEND_REQUEST_DELETE_USER_FAILURE: 'SEND_REQUEST_DELETE_USER_FAILURE',

  LOGOUT_HANDLER: 'LOGOUT_HANDLER',

  SEND_REQUEST_GET_ALL_PHOTOS: 'SEND_REQUEST_GET_ALL_PHOTOS',
  SEND_REQUEST_GET_ALL_PHOTOS_SUCCESS: 'SEND_REQUEST_GET_ALL_PHOTOS_SUCCESS',
  SEND_REQUEST_GET_ALL_PHOTOS_FAILURE: 'SEND_REQUEST_GET_ALL_PHOTOS_FAILURE',

  SEND_REQUEST_GET_DETAILS_PHOTOS: 'SEND_REQUEST_GET_DETAILS_PHOTOS',
  SEND_REQUEST_GET_DETAILS_PHOTOS_SUCCESS: 'SEND_REQUEST_GET_DETAILS_PHOTOS_SUCCESS',
  SEND_REQUEST_GET_DETAILS_PHOTOS_FAILURE: 'SEND_REQUEST_GET_DETAILS_PHOTOS_FAILURE',

  DELETE_DATA_FROM_STORE: 'DELETE_DATA_FROM_STORE',
  DELETE_PHOTO_FROM_STORE: 'DELETE_PHOTO_FROM_STORE',
};
